import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { BouncingGrid } from "@/components/BouncingGrid";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "PlayPath",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-zinc-50 dark:bg-zinc-950 flex flex-col min-h-screen`}
      >
        <header className="sticky top-0 z-50 w-full border-b border-zinc-200 dark:border-zinc-800 bg-white/80 dark:bg-black/80 backdrop-blur-xl">
          <div className="container mx-auto px-4 h-16 flex items-center justify-between">
            <a href="/" className="text-xl font-bold tracking-tight text-zinc-800 dark:text-zinc-100">
              PlayPath
            </a>
            <nav className="hidden md:flex items-center gap-6 text-sm font-medium text-zinc-600 dark:text-zinc-400">
              <a href="/planner" className="hover:text-black dark:hover:text-white transition-colors">Planner</a>
              <a href="/activities" className="hover:text-black dark:hover:text-white transition-colors">Activities</a>
              <a href="/routine" className="hover:text-black dark:hover:text-white transition-colors">My Routine</a>
              <a href="/parent-zone" className="hover:text-black dark:hover:text-white transition-colors">Parent Zone</a>
            </nav>
            <a href="/waitlist" className="md:hidden text-sm font-medium bg-zinc-900 text-white dark:bg-zinc-100 dark:text-black px-4 py-2 rounded-full">
              Join Waitlist
            </a>
          </div>
        </header>

        <BouncingGrid />

        <main className="flex-1 relative z-10">
          {children}
        </main>

        <footer className="border-t border-zinc-200 dark:border-zinc-800 bg-white dark:bg-black py-12">
          <div className="container mx-auto px-4 flex flex-col md:flex-row justify-between items-center gap-6">
            <div className="text-center md:text-left">
              <p className="font-semibold text-zinc-900 dark:text-zinc-100">PlayPath</p>
              <p className="text-sm text-zinc-500">Play with purpose.</p>
            </div>
            <nav className="flex gap-6 text-sm text-zinc-500">
              <a href="/safety" className="hover:text-black dark:hover:text-white">Safety & Privacy</a>
              <a href="/parent-zone" className="hover:text-black dark:hover:text-white">Parent Zone</a>
            </nav>
            <p className="text-xs text-zinc-400">© {new Date().getFullYear()} PlayPath</p>
          </div>
        </footer>
      </body>
    </html>
  );
}
